[features]
seeds = false
skip-lint = false

[programs.devnet]
vault = "DiUKSs93G6wBb5FZCjJ8NhknkaVDQht1yeeCTM8K8yPB"
mock_lender = "7fssoWBo1sjse4es9moMpMZm6Hpa9Kzb7U5KXXpYpp4g"

[programs.localnet]
vault = "DiUKSs93G6wBb5FZCjJ8NhknkaVDQht1yeeCTM8K8yPB"
mock_lender = "7fssoWBo1sjse4es9moMpMZm6Hpa9Kzb7U5KXXpYpp4g"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"